<MainScreen>:
    name: "main_screen"
    AnchorLayout:
        BoxLayout:
            orientation: "vertical"
            size_hint: 0.5, 0.5
            GridLayout:
                pos_hint: {"center_x": 0.5}
                size_hint_x: 0.35
                cols: 2
                Label:
                    text: "Hidden Hunger"
                    font_size: "25dp"
                    markup: True